SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `products`
  ADD COLUMN `quantity` INT UNSIGNED NULL DEFAULT NULL AFTER `sku`;

ALTER TABLE `product_variations`
  ADD COLUMN `quantity` INT UNSIGNED NULL DEFAULT NULL AFTER `sku`;

SET FOREIGN_KEY_CHECKS = 1;
